version: '2.1'

services:
  banque:
    image: banque
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3005:3005
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 bin/www
